# Generated by Django 6.0 on 2025-12-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_listing_description_listing_sold_listing_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="type",
            field=models.CharField(
                choices=[
                    ("R", "Records"),
                    ("C", "Clothing"),
                    ("P", "Posters"),
                    ("M", "Miscellaneous"),
                ],
                max_length=5,
            ),
        ),
    ]
